### PR TITLE
Drop ibid-with-locator when prev cite has same one (fix #241)

### LINKED ISSUE #241: Position logic not in line with CSL spec.?
I don't know Haskell. However, I've been reading the CSL spec and I've encountered what I think may be incorrect behavior within citeproc. In practical terms, given two repeated, identical citations with identical locators, the resulting position value should be _solely_ "Ibid", and not "ibid-with-locator".

So:

```
Lorem [@cross1973, p. 125] ipsum [@cross1973, p. 125].
```

should yield:

```
Lorem (Cross, Canaanite Myth, 125) ipsum (ibid.).
```

but, instead, we get 

```
Lorem (Cross, Canaanite Myth, 125) ipsum (ibid., 125).
```

The relevant portion of the spec is [HERE](http://docs.citationstyles.org/en/stable/specification.html?highlight=ibid#choose) (under "position").

The issue comes at the very last stipulation:

> **Preceding cite does have a locator:** if the current cite has the _same_ locator, the position of the current cite is “ibid”. If the locator differs the position is “ibid-with-locator”. If the current cite lacks a locator its only position is “subsequent”. 

As far as I can tell, this library only tests to see if a locator is supplied rather than if it matches the previous locator value. Thus, even if the current citation is identical to the previous one, the result is "ibid-with-locator" because, indeed, a locator is supplied.

I copied the CSL sheet that I was using and imported it into Zotero to see if the JS implementation worked as expected and, indeed, it did.

### PR DESCRIPTION
**Pull request by cormacrelf**
Still needs tests, I'm not sure how to generate the right expected input and output (which CSL do I use for that?)

```
  [@key]      => "first"
  [@key]      => "ibid"
  [@key, 53]  => "ibid-with-locator"
  [@key, 123] => "ibid-with-locator"
  [@key, 123] => "ibid"
  [@key]      => "subsequent"
```

See http://docs.citationstyles.org/en/stable/specification.html#locators.

I am a bit unsure about the spec here, with respect to multi-cite citations (option b).

Previously, any number of `@sameCitekey` with no different keys in the last ref would trigger an ibid, and the logic stopped at showing locators if they were available, otherwise not.

The spec appears to be concerned that you cannot know the correct one to match the locator against. It is a little bit clunky if you have `[@a, 1; @a, 2]` then `[@a, 3]`, where the page 3 citation gets "subsequent" even though there were only @a keys in the previous one. A flexible interpretation of the spec says "consisting of a single cite referencing the same item" means"all >= 1 cites in previous citation reference the same item as the current". That's what this PR does., which is mostly in line with the old behaviour.

You can still get to "subsequent" by doing `[@a, 1]` then `[@a]` or `[@a, 1; @a]`, but most people don't do this, because they look silly.

(Also note that tests/issue68 depends on on the >=1 behaviour.

### CODE REVIEW

**Comment by jgm** [comment]
Great! As for tests, you need to find a CSL that uses ibid.  We already have a bunch of csl files in the `tests/` directory; ideally you could use one of them.

Easiest way to create a test is to make a small markdown file that includes the needed references in metadata, and that tests the issue.  Then convert it to native:

    pandoc issue361.md -s -o tests/issue361.in.native

Then run pandoc-citeproc on this this to generated the "expected" result:

    pandoc tests/issue361.in.native -s -F pandoc-citeproc -o tests/issue361.expected.native

Check this carefully for correctness. (You can convert it to HTML to make this easier.)
If all is well, add `tests/issue361.*.native` to the repository.

**Comment by cormacrelf** [comment]
Ok, will do. That info would be good to find in a CONTRIBUTING.md or wiki entry.

**Comment by jgm** [comment]
I've added a CONTRIBUTING.md file, good suggestion.

**Comment by cormacrelf** [comment]
@jgm tests added, not sure if you've already got a thousand notifications but this one's ready.

File: src/Text/CSL/Reference.hs [hunk 1]
```diff
@@ -890,24 +890,50 @@ processCites rs cs
 
       procCs a [] = (a,[])
       procCs a (c:xs)
-          | isIbid,  isLocSet = go "ibid-with-locator"
-          | isIbid            = go "ibid"
-          | isElem            = go "subsequent"
-          | otherwise         = go "first"
+          | isIbid          = go (fromJust $ fmap ibidPosition prevSameCite)
```
Comment (jgm) [inline src/Text/CSL/Reference.hs]: `fromJust` (and partial functions generally) should be avoided.
IS there a sensible default we could use with `fromMaybe`?

Comment (jgm) [reply src/Text/CSL/Reference.hs]: Ah, I see, `isIbid` guarantees it's a Just. Even so, this is a code smell.  Can the whole thing be rewritten so it doesn't use `fromJust`?

Comment (cormacrelf) [reply src/Text/CSL/Reference.hs]: Yeah, good point. I've flipped it around and used fromMaybe.

For now and in future, with an updated PR would you prefer if I squashed and force pushed, or added a commit? You can always 'squash and merge' any extra commits in GitHub to abide by one commit per logical change later on.

Comment (jgm) [reply src/Text/CSL/Reference.hs]: For something like this, it's fine for me to squash and merge.
If a PR is large and contains several changes that should be kept distinct in the history, then it's better if you rebase them to avoid squashing everything into one commit. But in this case, one commit is the appropriate thing to  do, so squashing is fine.

File: src/Text/CSL/Reference.hs [hunk 2]
```diff
@@ -889,25 +889,51 @@ processCites rs cs
                         in res : procGr (a' ++ [[]]) xs
 
       procCs a [] = (a,[])
-      procCs a (c:xs)
-          | isIbid,  isLocSet = go "ibid-with-locator"
-          | isIbid            = go "ibid"
-          | isElem            = go "subsequent"
-          | otherwise         = go "first"
+      procCs a (c:xs) = let addCite    = init a ++ [last a ++ [c]]
```
Comment (jgm) [inline src/Text/CSL/Reference.hs]: `init` and `last` are partial functions, too.  So this will break if `a` is null.

Comment (cormacrelf) [reply src/Text/CSL/Reference.hs]: Those aren't even mine! I'll give it a go though.

Comment (jgm) [reply src/Text/CSL/Reference.hs]: Sorry, I didn't notice that at a quick glance. Well, there is a lot of ugly code in this code base, and cleaning it up as we work on it will help make it easier to figure out what is going on in the future.

Comment (cormacrelf) [reply src/Text/CSL/Reference.hs]: I think this whole function would be better off building the list from the front rather than from the back, don't you think?

Comment (cormacrelf) [reply src/Text/CSL/Reference.hs]: It worked out. Is there some kind of Haskell linter to run over the codebase that can catch these for us?

**Comment by jgm** [comment]
Cormac Relf <notifications@github.com> writes:

> It worked out. Is there some kind of Haskell linter to run over the codebase that can catch these for us?

hlint is the standard.  It may not catch this kind of thing, though.

**Comment by cormacrelf** [comment]
Actually, I've just thought of another edge case here. Same location, different locator type.

**Comment by jgm** [comment]
Excellent, thanks. Building from front seems much cleaner.  (I assume the order never matters?  At any rate, all the existing tests passed.)

**Comment by cormacrelf** [comment]
The order does matter once, when you decide which of a group of same-citekeys to compare to, but:

- I swapped two orders, the order of groups (acc) and the order within each group
- And each order gets swapped at two points in the code, so it cancels out.
  - addCite (and the little mini prepend in procGs) swaps once for each
  - the removed reverses on [this line](https://github.com/jgm/pandoc-citeproc/pull/361/commits/04f498fbddc996199a30ea30d741ef0fa12ecbcc#diff-9a381312c019ecdc1c29ccc97c82249cL916) swap each again.
- And the accumulated result is discarded.

But yes, indeed, the tests are a good safety harness.
